"""Cross-language interoperability tests using the canonical ACE test vectors.

The vectors live in ``ace-spec/test-vectors.json`` (generated by
``spec/generate-vectors.py`` from this SDK) and are shared with the TypeScript and
Swift SDKs to guarantee wire-format compatibility: identity derivation, X-Wing
draft-11 vector 1, conversationId, signData, signatures and a full encrypted
message that every SDK must decrypt to the same body.
"""

import base64
import json
import pathlib

import pytest

from ace import xwing
from ace.encryption import compute_conversation_id, get_ace_kem_salt
from ace.identity import SoftwareIdentity
from ace.messages import parse_message
from ace.security import ReplayDetector
from ace.signing import (
    build_sign_data,
    decode_signature,
    encode_payload,
    encode_signature,
    verify_signature,
)
from ace.state_machine import ThreadStateMachine
from ace.types import ACEMessage

_ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
VECTORS_PATH = _ROOT / "ace-spec" / "test-vectors.json"


def _load_vectors() -> dict:
    return json.loads(VECTORS_PATH.read_text())


def _b64(s: str) -> bytes:
    return base64.b64decode(s)


def _identity(agent: dict) -> SoftwareIdentity:
    return SoftwareIdentity(
        agent["scheme"],
        _b64(agent["signingPrivateKey"]),
        _b64(agent["encryptionPrivateKey"]),
    )


def test_vectors_file_exists():
    assert VECTORS_PATH.exists(), f"Missing shared test vectors at {VECTORS_PATH}"


def test_top_level_schema():
    v = _load_vectors()
    assert v["version"] == "1.0"
    assert set(v["agents"]) == {"alice", "bob"}
    assert set(v["xwing"]) == {"seed", "publicKey", "ciphertext", "sharedSecret"}
    assert {"aceKemSalt", "conversationId", "signData", "signature", "encryptedMessage"} <= set(v["vectors"])


def test_ace_kem_salt():
    v = _load_vectors()
    assert get_ace_kem_salt().hex() == v["vectors"]["aceKemSalt"]


def test_xwing_draft_vector():
    """X-Wing draft-11 vector 1: seed -> pk, (ct, seed) -> ss."""
    x = _load_vectors()["xwing"]
    seed = bytes.fromhex(x["seed"])
    assert len(seed) == xwing.SEED_SIZE
    assert xwing.public_key_from_seed(seed).hex() == x["publicKey"]
    assert xwing.decapsulate(bytes.fromhex(x["ciphertext"]), seed).hex() == x["sharedSecret"]


@pytest.mark.parametrize("name", ["alice", "bob"])
def test_identity_derivation(name):
    v = _load_vectors()
    a = v["agents"][name]
    assert len(_b64(a["encryptionPrivateKey"])) == 32
    idn = _identity(a)
    assert idn.get_signing_scheme() == a["scheme"]
    assert idn.get_ace_id() == a["aceId"]
    assert idn.get_address() == a["address"]
    assert base64.b64encode(idn.get_signing_public_key()).decode() == a["signingPublicKey"]
    assert base64.b64encode(idn.get_encryption_public_key()).decode() == a["encryptionPublicKey"]
    assert len(_b64(a["encryptionPublicKey"])) == 1216


def test_conversation_id():
    v = _load_vectors()
    alice_enc = _b64(v["agents"]["alice"]["encryptionPublicKey"])
    bob_enc = _b64(v["agents"]["bob"]["encryptionPublicKey"])
    assert compute_conversation_id(alice_enc, bob_enc) == v["vectors"]["conversationId"]
    # Symmetric: B<->A == A<->B
    assert compute_conversation_id(bob_enc, alice_enc) == v["vectors"]["conversationId"]


def test_sign_data():
    v = _load_vectors()
    sd = v["vectors"]["signData"]
    mp = sd["messagePayload"]

    kem_ct = _b64(mp["kemCiphertext"])
    assert kem_ct == b"\xaa" * 1120

    message_payload = encode_payload(
        mp["type"],
        mp["to"],
        mp["conversationId"],
        mp["messageId"],
        mp["threadId"],
        kem_ct,
        _b64(mp["ciphertext"]),
    )
    sign_data = build_sign_data(sd["action"], sd["aceId"], sd["timestamp"], message_payload)
    assert sign_data.hex() == sd["signDataHex"]


def test_ed25519_signature_verification():
    v = _load_vectors()
    sig_v = v["vectors"]["signature"]
    alice = v["agents"]["alice"]

    sign_data = bytes.fromhex(sig_v["signDataHex"])
    sig_bytes = decode_signature(sig_v["signatureValue"], "ed25519")
    pub_key = _b64(alice["signingPublicKey"])

    assert verify_signature(sign_data, sig_bytes, "ed25519", pub_key)


def test_cross_sign_and_verify():
    """Alice (ed25519) signs deterministically; must reproduce the fixture signature."""
    v = _load_vectors()
    alice = _identity(v["agents"]["alice"])

    sd = v["vectors"]["signData"]
    sign_data = bytes.fromhex(sd["signDataHex"])
    sig, scheme = alice.sign(sign_data)
    assert scheme == "ed25519"
    assert encode_signature(sig, "ed25519") == v["vectors"]["signature"]["signatureValue"]


def test_encrypted_message_decrypts_for_bob(monkeypatch):
    """Full wire message alice -> bob: verify signature, decrypt, compare body.

    The vector's timestamp is fixed, so the 5-minute freshness check is disabled
    and the replay horizon starts at 0 for this test only; every other pipeline
    step runs for real.
    """
    import ace.messages as messages_mod
    monkeypatch.setattr(messages_mod, "check_timestamp_freshness", lambda *_: None)

    v = _load_vectors()
    em = v["vectors"]["encryptedMessage"]
    assert em["from"] == "alice" and em["to"] == "bob"
    alice = v["agents"]["alice"]
    bob = _identity(v["agents"]["bob"])

    env = em["envelope"]
    assert env["type"] == "text"
    assert env["from"] == alice["aceId"]
    assert env["to"] == bob.get_ace_id()
    assert env["conversationId"] == v["vectors"]["conversationId"]
    assert len(_b64(env["encryption"]["kemCiphertext"])) == 1120

    msg = ACEMessage.from_dict(env)
    parsed = parse_message(
        msg,
        bob,
        _b64(alice["signingPublicKey"]),
        ThreadStateMachine(),
        # The fixed vector timestamp is far below a new store's horizon.
        ReplayDetector.from_export({"horizon": 0, "senderHorizons": {}, "entries": []}),
        sender_encryption_pub_key=_b64(alice["encryptionPublicKey"]),
    )
    assert parsed.body == em["expectedBody"]
    assert parsed.body == {"message": "hello from python"}
