"""ACE Protocol SDK — Agent Commerce Engine."""

__version__ = "0.3.0"

from ._encoding import (
    from_base64,
    is_ace_id,
    is_conversation_id,
    is_https_url,
    is_message_id,
    is_thread_id,
    to_base64,
)
from .audit import (
    AuditCheckpoint,
    AuditTree,
    AuditWitnessPolicy,
    AuditWitnessReceipt,
    audit_checkpoint_digest,
    audit_commitment,
    create_audit_checkpoint,
    create_audit_opening,
    create_audit_witness_receipt,
    verify_audit_checkpoint,
    verify_audit_consistency,
    verify_audit_inclusion,
    verify_audit_witness_quorum,
    verify_audit_witness_receipt,
)
from .auth import RelayAuthRequest, create_auth_headers, parse_auth_headers, verify_auth_headers
from .direct import deliver_direct_or_relay, post_direct
from .discovery import (
    VerifiedPeer,
    fetch_registration_file,
    is_blocked_address,
    validate_profile,
    verify_peer_record,
    verify_registration_file,
)
from .encryption import (
    compute_conversation_id,
    decrypt_with_seed,
    generate_kem_seed,
    kem_public_key_from_seed,
)
from .envelope import decode_envelope, envelope_fingerprint, verify_envelope_signature
from .errors import ACEError, ACEErrorCategory, ACEErrorCode
from .execution_request import (
    EXECUTION_REQUEST_SCHEMA,
    EXECUTION_REQUEST_SCHEMA_DIGEST,
    EXECUTION_REQUEST_TYPE,
    parse_execution_request,
)
from .ext import (
    COMMERCE_EXT,
    CommerceAccount,
    CommerceIntentExt,
    CommercePricing,
    CommerceProfileExt,
    ExtCarrier,
    ExtMap,
    commerce_ext,
    ext_canonical,
    intent_commerce_ext,
    validate_commerce_ext,
    validate_ext,
)
from .grants import (
    ResourcePolicy,
    create_execution_grant,
    execution_grant_digest,
    execution_intent_digest,
    is_execution_units,
    verify_execution_grant_chain,
)
from .identity import SoftwareIdentity, compute_ace_id
from .inbox import Inbox, InboxPrincipal, ReceiveOutcome, inbox_principal_from_own_record
from .limits import (
    DEFAULT_REPLAY_CAPACITY,
    KEM_CIPHERTEXT_SIZE,
    KEM_PUBLIC_KEY_SIZE,
    KEM_SEED_SIZE,
    MAX_DIRECT_BODY_BYTES,
    MAX_ENVELOPE_BYTES,
    MAX_EXT_BYTES,
    MAX_EXT_DEPTH,
    MAX_EXT_KEY_BYTES,
    MAX_EXT_KEYS,
    MAX_INBOX_PAGE,
    MAX_JSON_DEPTH,
    MAX_OPEN_THREADS_PER_PEER,
    MAX_PAYLOAD_BYTES,
    MAX_PLAINTEXT_BYTES,
    MAX_REGISTRATION_FILE_BYTES,
    MAX_THREAD_ID_LENGTH,
    OFFLINE_WINDOW_SECONDS,
    TIMESTAMP_WINDOW_SECONDS,
)
from .messages import (
    SchemaValidator,
    create_message,
    known_schema_digest,
    parse_message,
    validate_body,
)
from .outbox import Outbox
from .peers import PeerStore
from .principal import (
    PRINCIPAL_ROLES,
    PrincipalContext,
    PrincipalSigner,
    check_principal_rules,
    create_principal_record,
    is_caip10,
    load_request_record,
    parse_principal_record,
    principal_payload,
    principal_sign_data,
    validate_principal_record,
)
from .registration import (
    create_registration_file,
    create_registration_request,
    verify_registration_request,
)
from .relay import Intent, RelayClient, Webhook
from .replay import ReplayDetector
from .secure_mailbox import (
    DirectReply,
    PullResult,
    SecureMailbox,
    SecureRelayReplies,
    deliver_secure,
    open_secure_mailbox,
    secure_transport_for,
)
from .secure_transport import SecureTransport
from .session import MLSError, NativeMLSEngine, PairwiseMLS
from .state_machine import (
    ThreadEvent,
    ThreadHistoryEntry,
    ThreadSnapshot,
    ThreadState,
    ThreadStateMachine,
)
from .store import ACEStore, FileStore, MemoryStore, check_key, check_lock_name
from .threads import PendingSend, ThreadStore
from .types import (
    ECONOMIC_TYPES,
    MESSAGE_TYPES,
    PRINCIPAL_TYPES,
    SIGNING_SCHEMES,
    AcceptBody,
    ACEIdentity,
    ACEMessage,
    AgentProfile,
    Capability,
    ConfirmBody,
    DecisionBody,
    DeliverBody,
    DiscoverQuery,
    EncryptionEnvelope,
    HardwareBacking,
    IdentityTier,
    InfoBody,
    InvoiceBody,
    JSONObject,
    JSONValue,
    MessageType,
    OfferBody,
    ParsedMessage,
    PeerRecord,
    PrincipalKey,
    PrincipalRecord,
    ReceiptBody,
    RegistrationFile,
    RegistrationRequest,
    RejectBody,
    ReplayState,
    ReportBody,
    RequestBody,
    RfqBody,
    SignatureEnvelope,
    SigningConfig,
    SigningScheme,
    SoftwareIdentityExport,
    TextBody,
    is_economic_type,
    is_message_type,
    is_principal_type,
    is_signing_scheme,
)
from .webhook import WebhookNotification, verify_webhook_notification

__all__ = [
    "AuditCheckpoint",
    "AuditTree",
    "AuditWitnessReceipt",
    "AuditWitnessPolicy",
    "audit_checkpoint_digest",
    "create_audit_witness_receipt",
    "verify_audit_witness_receipt",
    "verify_audit_witness_quorum",
    "audit_commitment",
    "create_audit_opening",
    "create_audit_checkpoint",
    "verify_audit_checkpoint",
    "verify_audit_consistency",
    "verify_audit_inclusion",
    "__version__",
    # types
    "ACEIdentity",
    "SigningScheme",
    "IdentityTier",
    "HardwareBacking",
    "RegistrationFile",
    "SigningConfig",
    "Capability",
    "AgentProfile",
    "DiscoverQuery",
    "PeerRecord",
    "ACEMessage",
    "MessageType",
    "EncryptionEnvelope",
    "SignatureEnvelope",
    "RfqBody",
    "OfferBody",
    "AcceptBody",
    "RejectBody",
    "InvoiceBody",
    "ReceiptBody",
    "DeliverBody",
    "ConfirmBody",
    "InfoBody",
    "TextBody",
    "JSONValue",
    "JSONObject",
    "ParsedMessage",
    "ThreadState",
    "ThreadSnapshot",
    "ThreadHistoryEntry",
    "ThreadEvent",
    "ReplayState",
    "RegistrationRequest",
    "RelayAuthRequest",
    "ReceiveOutcome",
    "DirectReply",
    "PendingSend",
    "Intent",
    "ACEStore",
    "ACEErrorCode",
    "ACEErrorCategory",
    "SoftwareIdentityExport",
    "Webhook",
    "WebhookNotification",
    # values
    "ACEError",
    "MESSAGE_TYPES",
    "ECONOMIC_TYPES",
    "SIGNING_SCHEMES",
    "is_message_type",
    "is_economic_type",
    "is_signing_scheme",
    "MAX_PLAINTEXT_BYTES",
    "MAX_PAYLOAD_BYTES",
    "MAX_ENVELOPE_BYTES",
    "MAX_DIRECT_BODY_BYTES",
    "MAX_JSON_DEPTH",
    "MAX_EXT_KEYS",
    "MAX_EXT_KEY_BYTES",
    "MAX_EXT_BYTES",
    "MAX_EXT_DEPTH",
    "MAX_THREAD_ID_LENGTH",
    "MAX_OPEN_THREADS_PER_PEER",
    "TIMESTAMP_WINDOW_SECONDS",
    "OFFLINE_WINDOW_SECONDS",
    "MAX_REGISTRATION_FILE_BYTES",
    "MAX_INBOX_PAGE",
    "KEM_SEED_SIZE",
    "KEM_PUBLIC_KEY_SIZE",
    "KEM_CIPHERTEXT_SIZE",
    "DEFAULT_REPLAY_CAPACITY",
    "SoftwareIdentity",
    "compute_ace_id",
    "to_base64",
    "from_base64",
    "compute_conversation_id",
    "decrypt_with_seed",
    "kem_public_key_from_seed",
    "generate_kem_seed",
    "decode_envelope",
    "verify_envelope_signature",
    "envelope_fingerprint",
    "is_ace_id",
    "is_message_id",
    "is_thread_id",
    "is_conversation_id",
    "is_https_url",
    "create_message",
    "parse_message",
    "validate_body",
    "known_schema_digest",
    "SchemaValidator",
    "VerifiedPeer",
    "verify_peer_record",
    "verify_registration_file",
    "fetch_registration_file",
    "validate_profile",
    # namespaced extensions (02 § Profile Fields) and urn:ace:commerce:1 (04)
    "COMMERCE_EXT",
    "ExtCarrier",
    "ExtMap",
    "CommerceProfileExt",
    "CommerceIntentExt",
    "CommercePricing",
    "CommerceAccount",
    "validate_ext",
    "validate_commerce_ext",
    "ext_canonical",
    "commerce_ext",
    "intent_commerce_ext",
    "is_blocked_address",
    "create_registration_file",
    "create_registration_request",
    "verify_registration_request",
    "create_auth_headers",
    "parse_auth_headers",
    "verify_auth_headers",
    "ReplayDetector",
    "ThreadStateMachine",
    "ThreadStore",
    "PeerStore",
    "Inbox",
    "PullResult",
    "Outbox",
    "RelayClient",
    "MemoryStore",
    "FileStore",
    "check_key",
    "check_lock_name",
    # secure network boundary (13)
    "SecureMailbox",
    "SecureRelayReplies",
    "SecureTransport",
    # integration glue: receive boundary, sending side, own principal option
    "open_secure_mailbox",
    "secure_transport_for",
    "deliver_secure",
    "InboxPrincipal",
    "inbox_principal_from_own_record",
    "PairwiseMLS",
    "NativeMLSEngine",
    "MLSError",
    "verify_webhook_notification",
    "post_direct",
    "deliver_direct_or_relay",
    # principal (09)
    "PRINCIPAL_TYPES",
    "is_principal_type",
    "PrincipalRecord",
    "PrincipalKey",
    "PrincipalSigner",
    "PrincipalContext",
    "create_principal_record",
    "validate_principal_record",
    "principal_sign_data",
    "check_principal_rules",
    "PRINCIPAL_ROLES",
    "is_caip10",
    "principal_payload",
    "parse_principal_record",
    "load_request_record",
    "RequestBody",
    "DecisionBody",
    "ReportBody",
    "ResourcePolicy",
    "EXECUTION_REQUEST_SCHEMA",
    "EXECUTION_REQUEST_SCHEMA_DIGEST",
    "EXECUTION_REQUEST_TYPE",
    "parse_execution_request",
    "create_execution_grant",
    "execution_grant_digest",
    "execution_intent_digest",
    "is_execution_units",
    "verify_execution_grant_chain",
]
