"""ACE Protocol SDK — Agent Commerce Engine."""

__version__ = "0.2.0"

from ._encoding import (
    from_base64,
    is_ace_id,
    is_conversation_id,
    is_https_url,
    is_message_id,
    is_thread_id,
    to_base64,
)
from .auth import RelayAuthRequest, create_auth_headers, parse_auth_headers, verify_auth_headers
from .direct import deliver_direct_or_relay, post_direct
from .discovery import (
    VerifiedPeer,
    fetch_registration_file,
    is_blocked_address,
    validate_profile,
    verify_peer_record,
    verify_registration_file,
)
from .encryption import (
    compute_conversation_id,
    decrypt_with_seed,
    generate_kem_seed,
    kem_public_key_from_seed,
)
from .envelope import decode_envelope, envelope_fingerprint, verify_envelope_signature
from .errors import ACEError, ACEErrorCategory, ACEErrorCode
from .identity import SoftwareIdentity, compute_ace_id
from .inbox import DirectReply, Inbox, PullResult, ReceiveOutcome, ReceiveSource
from .limits import (
    DEFAULT_REPLAY_CAPACITY,
    KEM_CIPHERTEXT_SIZE,
    KEM_PUBLIC_KEY_SIZE,
    KEM_SEED_SIZE,
    MAX_DIRECT_BODY_BYTES,
    MAX_ENVELOPE_BYTES,
    MAX_INBOX_PAGE,
    MAX_JSON_DEPTH,
    MAX_OPEN_THREADS_PER_PEER,
    MAX_PAYLOAD_BYTES,
    MAX_PLAINTEXT_BYTES,
    MAX_REGISTRATION_FILE_BYTES,
    MAX_THREAD_ID_LENGTH,
    OFFLINE_WINDOW_SECONDS,
    TIMESTAMP_WINDOW_SECONDS,
)
from .messages import create_message, parse_message, validate_body
from .outbox import Outbox
from .peers import PeerStore
from .principal import (
    PrincipalContext,
    PrincipalSigner,
    check_principal_rules,
    create_principal_record,
    principal_sign_data,
    validate_principal_record,
)
from .registration import (
    create_registration_file,
    create_registration_request,
    verify_registration_request,
)
from .relay import Intent, RelayClient, Webhook
from .replay import ReplayDetector
from .state_machine import (
    ThreadEvent,
    ThreadHistoryEntry,
    ThreadSnapshot,
    ThreadState,
    ThreadStateMachine,
)
from .store import ACEStore, FileStore, MemoryStore
from .threads import PendingSend, ThreadStore
from .types import (
    ECONOMIC_TYPES,
    MESSAGE_TYPES,
    PRINCIPAL_TYPES,
    SIGNING_SCHEMES,
    AcceptBody,
    ACEIdentity,
    ACEMessage,
    AgentProfile,
    Capability,
    ChainInfo,
    ConfirmBody,
    DecisionBody,
    DeliverBody,
    DiscoverQuery,
    EncryptionEnvelope,
    HardwareBacking,
    IdentityTier,
    InfoBody,
    InvoiceBody,
    JSONObject,
    JSONValue,
    MessageType,
    OfferBody,
    ParsedMessage,
    PeerRecord,
    PricingInfo,
    PrincipalKey,
    PrincipalRecord,
    ProfilePricing,
    ReceiptBody,
    RegistrationFile,
    RegistrationRequest,
    RejectBody,
    ReplayState,
    ReportBody,
    RequestBody,
    RfqBody,
    SignatureEnvelope,
    SigningConfig,
    SigningScheme,
    SoftwareIdentityExport,
    TextBody,
    is_economic_type,
    is_message_type,
    is_principal_type,
    is_signing_scheme,
)
from .webhook import WebhookNotification, verify_webhook_notification

__all__ = [
    "__version__",
    # types
    "ACEIdentity",
    "SigningScheme",
    "IdentityTier",
    "HardwareBacking",
    "RegistrationFile",
    "SigningConfig",
    "Capability",
    "PricingInfo",
    "ChainInfo",
    "AgentProfile",
    "ProfilePricing",
    "DiscoverQuery",
    "PeerRecord",
    "ACEMessage",
    "MessageType",
    "EncryptionEnvelope",
    "SignatureEnvelope",
    "RfqBody",
    "OfferBody",
    "AcceptBody",
    "RejectBody",
    "InvoiceBody",
    "ReceiptBody",
    "DeliverBody",
    "ConfirmBody",
    "InfoBody",
    "TextBody",
    "JSONValue",
    "JSONObject",
    "ParsedMessage",
    "ThreadState",
    "ThreadSnapshot",
    "ThreadHistoryEntry",
    "ThreadEvent",
    "ReplayState",
    "RegistrationRequest",
    "RelayAuthRequest",
    "ReceiveSource",
    "ReceiveOutcome",
    "DirectReply",
    "PendingSend",
    "Intent",
    "ACEStore",
    "ACEErrorCode",
    "ACEErrorCategory",
    "SoftwareIdentityExport",
    "Webhook",
    "WebhookNotification",
    # values
    "ACEError",
    "MESSAGE_TYPES",
    "ECONOMIC_TYPES",
    "SIGNING_SCHEMES",
    "is_message_type",
    "is_economic_type",
    "is_signing_scheme",
    "MAX_PLAINTEXT_BYTES",
    "MAX_PAYLOAD_BYTES",
    "MAX_ENVELOPE_BYTES",
    "MAX_DIRECT_BODY_BYTES",
    "MAX_JSON_DEPTH",
    "MAX_THREAD_ID_LENGTH",
    "MAX_OPEN_THREADS_PER_PEER",
    "TIMESTAMP_WINDOW_SECONDS",
    "OFFLINE_WINDOW_SECONDS",
    "MAX_REGISTRATION_FILE_BYTES",
    "MAX_INBOX_PAGE",
    "KEM_SEED_SIZE",
    "KEM_PUBLIC_KEY_SIZE",
    "KEM_CIPHERTEXT_SIZE",
    "DEFAULT_REPLAY_CAPACITY",
    "SoftwareIdentity",
    "compute_ace_id",
    "to_base64",
    "from_base64",
    "compute_conversation_id",
    "decrypt_with_seed",
    "kem_public_key_from_seed",
    "generate_kem_seed",
    "decode_envelope",
    "verify_envelope_signature",
    "envelope_fingerprint",
    "is_ace_id",
    "is_message_id",
    "is_thread_id",
    "is_conversation_id",
    "is_https_url",
    "create_message",
    "parse_message",
    "validate_body",
    "VerifiedPeer",
    "verify_peer_record",
    "verify_registration_file",
    "fetch_registration_file",
    "validate_profile",
    "is_blocked_address",
    "create_registration_file",
    "create_registration_request",
    "verify_registration_request",
    "create_auth_headers",
    "parse_auth_headers",
    "verify_auth_headers",
    "ReplayDetector",
    "ThreadStateMachine",
    "ThreadStore",
    "PeerStore",
    "Inbox",
    "PullResult",
    "Outbox",
    "RelayClient",
    "MemoryStore",
    "FileStore",
    "verify_webhook_notification",
    "post_direct",
    "deliver_direct_or_relay",
    # principal (09)
    "PRINCIPAL_TYPES",
    "is_principal_type",
    "PrincipalRecord",
    "PrincipalKey",
    "PrincipalSigner",
    "PrincipalContext",
    "create_principal_record",
    "validate_principal_record",
    "principal_sign_data",
    "check_principal_rules",
    "RequestBody",
    "DecisionBody",
    "ReportBody",
]
